### ISSUE TITLE
Views compile issue

### ISSUE THREAD

**Issue by cpiock** [daffl/can-compile#29]
I compile my views with this

```js
 cancompile: {
      options: {
        version: '2.1.1'
      },
      dist: {        
        src: ['**/*.mustache'],
        dest: 'production/views.production.js'
      }
    },
```

and concat it with this

```js
concat: {
      dist: {
          src: [
          'bower_components/jquery/dist/jquery.js',
          'bower_components/canjs/can.jquery.js',
          'bower_components/bootstrap/dist/js/bootstrap.js',
          //'js/**/*.js'
              'js/models/placetype.js',
              'js/models/place.js',
              'js/components/place/filter/filter.js',
              'js/components/place/list/list.js',
              'js/components/place/item/item.js',
              'js/components/placetype/filter/filter.js',
              'js/components/place/map/map.js',
              'js/pages/test/home/home.js',
              'js/pages/test/place/place.js',
              'js/pages/home/home.js',
              'js/pages/about/about.js',
              'js/pages/place/place.js',
          'js/app.js', // You app
          '<%= cancompile.dist.dest %>' // The compiled views
        ],
        dest: 'production/production.js'
      }
```

But if i run my app with the created production.js it tell's me "can.view: No template or empty template"

Here an example of a controller:

```
    can.Component.extend({
        tag: 'placetypefilter',
        template: can.view('js/components/placetype/filter/views/filter.mustache'),
```

In the views.production.js i have code like this:

```
can.view.preloadStringRenderer('\js\components\place\filter\views\filter_mustache', .....
```

**Comment by daffl** [comment]
I'd be this is a windows path separator problem. Your view preload function should convert the name into something like

```js
can.view.preloadStringRenderer('js_components_place_filter_views_filter_mustache',
```

**Comment by daffl** [comment]
It is using `can.view.toId` at https://github.com/daffl/can-compile/blob/master/lib/compile.js#L59.

**Comment by daffl** [comment]
This should be solvable by providing a custom normalizer though:

```js
var path = require('path');

cancompile: {
  options: {
    version: '2.1.1',
    normalizer: function(filename) {
      return filename.replace(new RegExp(path.sep, 'g'), '/');
    }
  }
}
```

**Comment by cpiock** [comment]
Warning: Object function (filename) {
          return filename.replace(new RegExp(path.sep, 'g'), '/');
      } has no method 'indexOf' Use --force to continue.

**Comment by daffl** [comment]
Well what does filename look like? I guess `filename.toString().replace(new RegExp(path.sep, 'g'), '/').substr(1);` is an option, too.

**Comment by cpiock** [comment]
i created this 
cancompile: {
      options: {
        version: '2.1.1'
      },
      dist: {        
        src: ['**/*.mustache'],
        dest: 'production/views.production.js'
      },
      normalizer: function (filename) {
          return filename.replace(new RegExp(path.sep, 'g'), '/');
      },
    },

was filename only a placeholder? sorry i'am a grunt newbie :-)

**Comment by cpiock** [comment]
oh i think i found the problem. :-)
the normalizer was in the wrong place

cancompile: {
      options: {
          version: '2.1.1',
          normalizer: function (filename) {
              return filename.replace(new RegExp(path.sep, 'g'), '/');
          },
      },    
      dist: {        
        src: ['**/*.mustache'],
        dest: 'production/views.production.js'
      }
    },

**Comment by daffl** [comment]
Cool. If that works I'll probably make a new patch release that takes this into consideration so you should be able to remove the normalizer (but don't have to). This hasn't been tested on Windows a lot (in fact I think you're the first one that got it working ;).

**Comment by cpiock** [comment]
if it works i will tell you. now it fails on the first  view. i think the regex has a problem i will check this. it should replace "/" with "_". right?

**Comment by cpiock** [comment]
can you explain me this: new RegExp(path.sep, 'g') 
Path.sep = '_' o '/'
what does g mean?

**Comment by marshallswain** [comment]
It looks for all instances of the match.

http://stackoverflow.com/questions/12993629/the-g-flag-in-regular-expressions
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp

**Comment by daffl** [comment]
Also `path.sep` should be `\` in Windows. Basically we want to replace every `\` with `/` so that `can.view.toId` works right.

**Comment by cpiock** [comment]
ok changed the normalizer to this 
 normalizer: function (filename) {              
              return filename.replace(new RegExp('\\\\', 'g'), '/');
          },

Know it compiles my views and i the views.production.js i have this:
can.view.preloadStringRenderer('js_components_place_filter_views_filter_mustache'

But my production.js doesn't work.
 GET http://localhost:57253/frontend/production/js/components/place/item/views/view.mustache 404

**Comment by daffl** [comment]
Can you send a `views.production.js` and the `can.view` call that doesn't work?

**Comment by cpiock** [comment]
Here my can view call:
template: can.view('js/components/placetype/filter/views/filter.mustache'),

the views.production.js i send to your email. every can.view call fails with 404

**Comment by daffl** [comment]
It turned out that the Component tags were not dash-separated. Unfortunately Mustache allows component names without a separating dash but they do not seem to work in production.
