### ISSUE TITLE
can-compile doesn't work offline

### ISSUE THREAD

**Issue by ccummings** [daffl/can-compile#30]
jQuery and CanJS are included from external locations so if you are offline can-compile will not work. They are included here: https://github.com/daffl/can-compile/blob/master/lib/compile.js#L11

Maybe each library should be local?

**Comment by daffl** [comment]
It should but I didn't find a good way to get the different versions. They could ship with the repository I guess. Or through bower installing maybe (but we don't want to install every available version)?

**Comment by ccummings** [comment]
What about adding an option that configures the path to where CanJS is? That let's can-compile just use the version the user has installed and doesn't make any assumptions about the rest of the stack (bower, npm, jspm, etc).

Depending on version, some template engines are in core vs. plugins which isn't accounted for now.

**Comment by daffl** [comment]
That could work but what do we do if someone uses a module loader?

**Comment by ccummings** [comment]
Once CanJS 2.2.0 is on npm we could add it as a dependency and load it from node_modules.

**Comment by daffl** [comment]
I think this can be considered closed via #36.
